version: '3.8'

services:
  kong-migrations:
    image: kong:3.4
    container_name: kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: host.docker.internal
      KONG_PG_PORT: 5432
      KONG_PG_USER: falaqmsi
      KONG_PG_PASSWORD: Rubysa179596
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kong:
    image: kong:3.4
    container_name: kong-gateway
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: host.docker.internal
      KONG_PG_PORT: 5432
      KONG_PG_USER: falaqmsi
      KONG_PG_PASSWORD: Rubysa179596
      KONG_PG_DATABASE: kong
      KONG_PROXY_LISTEN: 0.0.0.0:9545
      KONG_ADMIN_LISTEN: 0.0.0.0:9546
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:9547
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_GUI_ERROR_LOG: /dev/stderr
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    ports:
      - "9545:9545"
      - "9546:9546"
      - "9547:9547"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
